export const queryKeys = {
  auth: {
    root: ['auth'] as const,
    session: () => [...queryKeys.auth.root, 'session'] as const,
  },
  bitacora: {
    root: ['bitacora'] as const,
    list: (filters: unknown) => [...queryKeys.bitacora.root, 'list', filters] as const,
    resumen: () => [...queryKeys.bitacora.root, 'resumen'] as const,
  },
  devTools: {
    root: ['dev-tools'] as const,
    call: (path: string) => [...queryKeys.devTools.root, path] as const,
  },
  sitio: {
    root: ['sitio'] as const,
    home: () => [...queryKeys.sitio.root, 'home'] as const,
    contacto: () => [...queryKeys.sitio.root, 'contacto'] as const,
  },
  portfolio: {
    root: ['portfolio'] as const,
    list: () => [...queryKeys.portfolio.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.portfolio.root, 'detail', id] as const,
  },
  servicios: {
    root: ['servicios'] as const,
    list: () => [...queryKeys.servicios.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.servicios.root, 'detail', id] as const,
  },
  faq: {
    root: ['faq'] as const,
    list: () => [...queryKeys.faq.root, 'list'] as const,
  },
  promociones: {
    root: ['promociones'] as const,
    list: () => [...queryKeys.promociones.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.promociones.root, 'detail', id] as const,
  },
  testimonios: {
    root: ['testimonios'] as const,
    list: () => [...queryKeys.testimonios.root, 'list'] as const,
    destacados: () => [...queryKeys.testimonios.root, 'destacados'] as const,
    create: () => [...queryKeys.testimonios.root, 'create'] as const,
  },
  agenda: {
    root: ['agenda'] as const,
    disponibilidad: (filters: unknown) => [...queryKeys.agenda.root, 'disponibilidad', filters] as const,
  },
  presupuestos: {
    root: ['presupuestos'] as const,
    create: () => [...queryKeys.presupuestos.root, 'create'] as const,
  },
  publicHome: {
    root: ['public-home'] as const,
  },
  adminDashboard: {
    root: ['admin-dashboard'] as const,
  },
  eventos: { root: ['eventos'] as const, list: () => ['eventos', 'list'] as const, detail: (id: string) => ['eventos', 'detail', id] as const },
  fotos: { root: ['fotos'] as const, list: () => ['fotos', 'list'] as const, detail: (id: string) => ['fotos', 'detail', id] as const },
  favoritos: { root: ['favoritos'] as const, list: () => ['favoritos', 'list'] as const },
  carrito: { root: ['carrito'] as const, actual: () => ['carrito', 'actual'] as const },
  pedidos: { root: ['pedidos'] as const, list: () => ['pedidos', 'list'] as const, detail: (id: string) => ['pedidos', 'detail', id] as const },
  descargas: { root: ['descargas'] as const, list: () => ['descargas', 'list'] as const, detail: (id: string) => ['descargas', 'detail', id] as const },
  historial: { root: ['historial'] as const, miHistorial: () => ['historial', 'mi-historial'] as const },
  notificaciones: { root: ['notificaciones'] as const, list: () => ['notificaciones', 'list'] as const },
  perfil: { root: ['perfil'] as const, current: () => ['perfil', 'current'] as const },
  admin: {
    root: ['admin'] as const,
    dashboard: () => ['admin', 'dashboard'] as const,
    operaciones: () => ['admin', 'operaciones'] as const,
    eventos: () => ['admin', 'eventos'] as const,
    fotos: () => ['admin', 'fotos'] as const,
    clientes: () => ['admin', 'clientes'] as const,
    pedidos: () => ['admin', 'pedidos'] as const,
    descargas: () => ['admin', 'descargas'] as const,
    presupuestos: () => ['admin', 'presupuestos'] as const,
    agenda: () => ['admin', 'agenda'] as const,
    sesionesPrivadas: () => ['admin', 'sesiones-privadas'] as const,
    portfolio: () => ['admin', 'portfolio'] as const,
    servicios: () => ['admin', 'servicios'] as const,
    faq: () => ['admin', 'faq'] as const,
    notificaciones: () => ['admin', 'notificaciones'] as const,
    plantillas: () => ['admin', 'plantillas'] as const,
    ventas: () => ['admin', 'ventas'] as const,
    cupones: () => ['admin', 'cupones'] as const,
    promociones: () => ['admin', 'promociones'] as const,
    testimonios: () => ['admin', 'testimonios'] as const,
    carritosAbandonados: () => ['admin', 'carritos-abandonados'] as const,
    reportesVentas: (filters?: unknown) => ['admin', 'reportes-ventas', filters] as const,
  },
} as const;
