export const queryKeys = {
  auth: {
    root: ['auth'] as const,
    session: () => [...queryKeys.auth.root, 'session'] as const,
  },
  bitacora: {
    root: ['bitacora'] as const,
    list: (filters: unknown) => [...queryKeys.bitacora.root, 'list', filters] as const,
    detail: (id: string) => [...queryKeys.bitacora.root, 'detail', id] as const,
    resumen: () => [...queryKeys.bitacora.root, 'resumen'] as const,
  },
  devTools: {
    root: ['dev-tools'] as const,
    call: (path: string) => [...queryKeys.devTools.root, path] as const,
    endpoint: (method: string, path: string) => [...queryKeys.devTools.root, method, path] as const,
  },
  sitio: {
    root: ['sitio'] as const,
    home: () => [...queryKeys.sitio.root, 'home'] as const,
    contacto: () => [...queryKeys.sitio.root, 'contacto'] as const,
    perfilPublico: () => [...queryKeys.sitio.root, 'perfil-publico'] as const,
    perfilFotografa: () => [...queryKeys.sitio.root, 'perfil-fotografa'] as const,
    perfilFotografaAdmin: () => [...queryKeys.sitio.root, 'perfil-fotografa-admin'] as const,
  },
  portfolio: {
    root: ['portfolio'] as const,
    list: () => [...queryKeys.portfolio.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.portfolio.root, 'detail', id] as const,
  },
  servicios: {
    root: ['servicios'] as const,
    list: () => [...queryKeys.servicios.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.servicios.root, 'detail', id] as const,
  },
  faq: {
    root: ['faq'] as const,
    list: () => [...queryKeys.faq.root, 'list'] as const,
  },
  promociones: {
    root: ['promociones'] as const,
    list: () => [...queryKeys.promociones.root, 'list'] as const,
    detail: (id: string) => [...queryKeys.promociones.root, 'detail', id] as const,
  },
  testimonios: {
    root: ['testimonios'] as const,
    list: () => [...queryKeys.testimonios.root, 'list'] as const,
    destacados: () => [...queryKeys.testimonios.root, 'destacados'] as const,
    create: () => [...queryKeys.testimonios.root, 'create'] as const,
  },
  agenda: {
    root: ['agenda'] as const,
    disponibilidad: (filters: unknown) => [...queryKeys.agenda.root, 'disponibilidad', filters] as const,
    adminList: (filters?: unknown) => [...queryKeys.agenda.root, 'admin-list', filters] as const,
  },
  presupuestos: {
    root: ['presupuestos'] as const,
    create: () => [...queryKeys.presupuestos.root, 'create'] as const,
  },
  publicHome: {
    root: ['public-home'] as const,
  },
  adminDashboard: {
    root: ['admin-dashboard'] as const,
  },
  eventos: { root: ['eventos'] as const, list: () => ['eventos', 'list'] as const, paginado: (filters?: unknown) => ['eventos', 'paginado', filters] as const, detail: (id: string) => ['eventos', 'detail', id] as const, paquetes: (eventoId: string) => ['eventos', 'paquetes', eventoId] as const, comentarios: (eventoId: string) => ['eventos', 'comentarios', eventoId] as const },
  fotos: { root: ['fotos'] as const, byEvento: (eventoId: string) => ['fotos', 'evento', eventoId] as const, paginadasPorEvento: (eventoId: string, filters?: unknown) => ['fotos', 'evento', eventoId, 'paginado', filters] as const, detail: (id: string) => ['fotos', 'detail', id] as const },
  comentariosFotos: { root: ['fotos-comentarios'] as const, list: (fotoId: string) => ['fotos-comentarios', fotoId] as const },
  favoritos: { root: ['favoritos'] as const, list: () => ['favoritos', 'list'] as const, eventosPaginado: (filters?: unknown) => ['favoritos', 'eventos', 'paginado', filters] as const, fotosPaginado: (filters?: unknown) => ['favoritos', 'fotos', 'paginado', filters] as const },
  carrito: { root: ['carrito'] as const, actual: () => ['carrito', 'actual'] as const },
  pedidos: { root: ['pedidos'] as const, list: () => ['pedidos', 'list'] as const, paginado: (filters?: unknown) => ['pedidos', 'paginado', filters] as const, detail: (id: string) => ['pedidos', 'detail', id] as const },
  descargas: { root: ['descargas'] as const, list: () => ['descargas', 'list'] as const, detail: (id: string) => ['descargas', 'detail', id] as const },
  historial: { root: ['historial'] as const, miHistorial: () => ['historial', 'mi-historial'] as const },
  notificaciones: { root: ['notificaciones'] as const, list: () => ['notificaciones', 'list'] as const },
  perfil: { root: ['perfil'] as const, current: () => ['perfil', 'current'] as const },
  admin: {
    root: ['admin'] as const,
    dashboard: () => ['admin', 'dashboard'] as const,
    operaciones: () => ['admin', 'operaciones'] as const,
    eventos: () => ['admin', 'eventos'] as const,
    fotos: () => ['admin', 'fotos'] as const,
    fotosEvento: (eventoId: string) => ['admin', 'fotos', 'evento', eventoId] as const,
    fotosEventoPaginado: (eventoId: string, filters?: unknown) => ['admin', 'fotos', 'evento', eventoId, 'paginado', filters] as const,
    clientes: () => ['admin', 'clientes'] as const,
    pedidos: () => ['admin', 'pedidos'] as const,
    descargas: () => ['admin', 'descargas'] as const,
    presupuestos: () => ['admin', 'presupuestos'] as const,
    agenda: (filters?: unknown) => ['admin', 'agenda', filters] as const,
    sesionesPrivadas: () => ['admin', 'sesiones-privadas'] as const,
    portfolio: () => ['admin', 'portfolio'] as const,
    servicios: () => ['admin', 'servicios'] as const,
    faq: () => ['admin', 'faq'] as const,
    notificaciones: () => ['admin', 'notificaciones'] as const,
    plantillas: () => ['admin', 'plantillas'] as const,
    ventas: () => ['admin', 'ventas'] as const,
    cupones: () => ['admin', 'cupones'] as const,
    promociones: () => ['admin', 'promociones'] as const,
    testimonios: () => ['admin', 'testimonios'] as const,
    carritosAbandonados: () => ['admin', 'carritos-abandonados'] as const,
    reportesVentas: (filters?: unknown) => ['admin', 'reportes-ventas-resumen', filters] as const,
    notasInternas: (entidadTipo: string, entidadId: string) => ['admin', 'notas-internas', entidadTipo, entidadId] as const,
    sesionPrivada: (id: string) => ['admin', 'sesiones-privadas', id] as const,
    fotosPrivadas: (id: string) => ['admin', 'sesiones-privadas', id, 'fotos'] as const,
    paquetesEvento: (eventoId: string) => ['admin', 'eventos', eventoId, 'paquetes'] as const,
    miPerfil: () => ['admin', 'mi-perfil'] as const,
  },
} as const;
